[http]
  [http.middlewares]

    [http.middlewares.api-stripprefix.stripPrefix]
      prefixes = ["/api/statistics", "/api/word", "/api/answer", "/api/state", "/api/bff"]

  [http.routers]

    [http.routers.words]
      service = "words"
      rule = "PathPrefix(`/api/word`)"
      middlewares = ["api-stripprefix"] 

    [http.routers.answers]
      service = "answers"
      rule = "PathPrefix(`/api/answer`)"
      middlewares = ["api-stripprefix"]

    [http.routers.stats]
      service = "statistics"
      rule = "PathPrefix(`/api/statistics`)"
      middlewares = ["api-stripprefix"]
    
    [http.routers.state]
      service = "state"
      rule = "PathPrefix(`/api/state`)"
      middlewares = ["api-stripprefix"] 

    [http.routers.bff]
      service = "bff"
      rule = "PathPrefix(`/api/bff`)"
      middlewares = ["api-stripprefix"] 

  [http.services]

    [http.services.words]
      [http.services.words.loadBalancer]
        [[http.services.words.loadBalancer.servers]]
          url = "http://127.0.0.1:5100"

    [http.services.answers]
      [http.services.answers.loadBalancer]
        [[http.services.answers.loadBalancer.servers]]
          url = "http://127.0.0.1:5200"

    [http.services.statistics]
      [http.services.statistics.loadBalancer]
        [[http.services.statistics.loadBalancer.servers]]
          url = "http://127.0.0.1:5300"
        [[http.services.statistics.loadBalancer.servers]]
          url = "http://127.0.0.1:5301"
        [[http.services.statistics.loadBalancer.servers]]
          url = "http://127.0.0.1:5302"

    [http.services.state]
      [http.services.state.loadBalancer]
        [[http.services.state.loadBalancer.servers]]
          url = "http://127.0.0.1:5400"

    [http.services.bff]
      [http.services.bff.loadBalancer]
        [[http.services.bff.loadBalancer.servers]]
          url = "http://127.0.0.1:5500"

